trseeker:
    # os: linux64
    os: WIN
    root_dir: /root/Dropbox/workspace/trseeker
    work_dir: /home
blast_settings:
    blast_location:
    blast_location_NIX: /root/ncbi-blast-2.2.26+/bin/legacy_blast.pl bl2seq
    blast_location_WIN: c:\Program Files\NCBI\blast-2.2.26+\bin\legacy_blast.pl bl2seq.exe
    repbase_db_folder: /home/rebase_blast_db/repbase
    jellyfish_location: /home/akomissarov/libs/jellyfish-1.1.11/bin/jellyfish
    blast_e: 1e-20
    blast_b: 20000000
    blast_v: 20000000
trf_settings:
    trf_location: /home/akomissarov/libs/trf407b.linux64
    trf_location_mac: /Users/akomissarov/libs/trf407b.macos64
    trf_location_WIN: e:/trf407b.dos.exe
    trf_match: 2
    trf_mismatch: 5
    trf_indel: 7
    trf_p: 80
    trf_q: 10
    trf_threshold: 50
    trf_length: 2000
    trf_param_postfix: 2.5.7.80.10.50.2000
    trf_masked_file: False
    trf_flanked_data: True
    trf_data_file: True
    trf_nohtml: True
    overlapping_cutoff: 10
    overlapping_cutoff_proc: 30
    overlapping_gc_diff: 0.05
jellyfish_settings:
    threads: 30
    hash_size: 50G
    hash_bits: 10
    both_strands: "--both-strands"
ngrams_settings:
    ngram_length: 23
    ngram_m: 10000000